#!/bin/sh

usage() {
  echo "Usage: $0 -c <cluster> [-s <service_name>]"
  echo " <cluster> The name of the ECS Cluster you wish to get EC2 IPs for"
  echo " <service_name> Filter private ips by service name"
  exit 1
}

while getopts "c:s:" o; do
  case "${o}" in
    c)
      CLUSTER=${OPTARG}
      ;;
    s)
      SERVICE_NAME=${OPTARG}
      ;;
    *)
      usage
      ;;
  esac
done
shift $((OPTIND-1))

if [[ -z "${CLUSTER}" ]] ; then
  usage
fi

if [[ -z "${SERVICE_NAME}" ]] ; then
  LISTED_TASKS=$(aws ecs list-tasks --cluster $CLUSTER --output text | cut -f2)
else
  LISTED_TASKS=$(aws ecs list-tasks --cluster $CLUSTER --service-name $SERVICE_NAME --output text | cut -f2)

  if [[ -z "${LISTED_TASKS}" ]] ; then
    exit 1
  fi
fi

TASK_CONTAINER_INSTANCE_ARNS=$(aws ecs describe-tasks --cluster $CLUSTER --tasks $LISTED_TASKS --query 'tasks[*].[containerInstanceArn]' --output text)

EC2_IDS=$(aws ecs describe-container-instances --cluster $CLUSTER --container-instances $TASK_CONTAINER_INSTANCE_ARNS --query 'containerInstances[*].[ec2InstanceId]' --output text)

aws ec2 describe-instances --instance-ids $EC2_IDS --query 'Reservations[*].Instances[*].NetworkInterfaces[*].PrivateIpAddresses[0].[PrivateIpAddress]' --output text
